<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace WBT\API\Weibotui;

use Bluefin\App;
use Bluefin\Common;
use Bluefin\Service;
use Bluefin\Data\Model;
use Bluefin\Data\Database;

use WBT\Model\Weibotui\UserDepositStatus;
use WBT\Model\Weibotui\UserDepositRecord;

class UserDepositRecordAPI extends Service
{
    public function create()
    {
        $aclStatus = UserDepositRecord::checkActionPermission(Model::OP_CREATE);
        if ($aclStatus !== Model::ACL_ACCEPTED)
        {
            throw new \Bluefin\Exception\RequestException(null, $aclStatus);
        }

        $userDepositRecord = new UserDepositRecord();
        $userDepositRecord->reset($this->_app->request()->getPostParams());
        return $userDepositRecord->insert();
    }


    public function doCancel($userDepositRecordID)
    {
        UserDepositRecord::doCancel($userDepositRecordID, $this->_app->request()->getPostParams());

        return 1;
    }

    public function doPay($userDepositRecordID)
    {
        UserDepositRecord::doPay($userDepositRecordID, $this->_app->request()->getPostParams());

        return 1;
    }

    public function doPaymentSucceed($userDepositRecordID)
    {
        UserDepositRecord::doPaymentSucceed($userDepositRecordID, $this->_app->request()->getPostParams());

        return 1;
    }

    public function doPaymentFail($userDepositRecordID)
    {
        UserDepositRecord::doPaymentFail($userDepositRecordID, $this->_app->request()->getPostParams());

        return 1;
    }
}
?>