<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under WBT\Business namespace.
namespace WBT\Model\Weibotui;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class AdminLoginRecord extends Model
{
    const ADMIN_LOGIN_RECORD_ID = 'admin_login_record_id';
    const _CREATED_AT = '_created_at';
    const IP_ADDRESS = 'ip_address';
    const ADMIN = 'admin';

    const WITH_ADMIN = 'admin_login_record.admin:admin.admin_id';


    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'weibotui',
                'admin_login_record',
                'admin_login_record_id',
                [
                    'admin_login_record_id' => ['name' => _META_('weibotui.admin_login_record.admin_login_record_id'), 'type' => 'uuid', 'default' => new \Bluefin\Data\Functor\AutoUUID(), 'required' => true, 'rou' => true],
                    '_created_at' => ['name' => _META_('weibotui.admin_login_record._created_at'), 'type' => 'timestamp', 'required' => true, 'default' => new DbExpr('NOW()'), 'roc' => true, 'rou' => true],
                    'ip_address' => ['name' => _META_('weibotui.admin_login_record.ip_address'), 'type' => 'ipv4', 'default' => new \Bluefin\Data\Functor\VarTextProvider("{{gateway.client_ip}}"), 'required' => true],
                    'admin' => ['name' => _META_('weibotui.admin_login_record.admin'), 'type' => 'int', 'length' => 10, 'min' => 1000, 'required' => true, 'default' => new \Bluefin\Data\Functor\VarTextProvider("{{auth.wbt_admin.admin_id}}")],
                ],
                [
                    'auto_uuid' => 'admin_login_record_id',
                    'create_timestamp' => '_created_at',
                ],
                [
                    'admin' => self::WITH_ADMIN,
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets uuid
     * @return string
     */
    public function getAdminLoginRecordID()
    {
        return $this->__get(self::ADMIN_LOGIN_RECORD_ID);
    }

    /**
     * Sets uuid
     * @param string $value
     * @return AdminLoginRecord
     */
    public function setAdminLoginRecordID($value)
    {
        $this->__set(self::ADMIN_LOGIN_RECORD_ID, $value);

        return $this;
    }

    /**
     * Gets createdat
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->__get(self::_CREATED_AT);
    }

    /**
     * Sets createdat
     * @param string $value
     * @return AdminLoginRecord
     */
    public function setCreatedAt($value)
    {
        $this->__set(self::_CREATED_AT, $value);

        return $this;
    }

    /**
     * Gets 登录地址
     * @return string
     */
    public function getIPAddress()
    {
        return $this->__get(self::IP_ADDRESS);
    }

    /**
     * Sets 登录地址
     * @param string $value
     * @return AdminLoginRecord
     */
    public function setIPAddress($value)
    {
        $this->__set(self::IP_ADDRESS, $value);

        return $this;
    }

    /**
     * Gets 内部用户
     * @return int
     */
    public function getAdmin()
    {
        return $this->__get(self::ADMIN);
    }

    /**
     * Sets 内部用户
     * @param int $value
     * @return AdminLoginRecord
     */
    public function setAdmin($value)
    {
        $this->__set(self::ADMIN, $value);

        return $this;
    }

    /**
     * @param bool $new
     * @return \WBT\Model\Weibotui\Admin
     */
    public function getAdmin_($new = false)
    {
        if ($new)
        {
            return new \WBT\Model\Weibotui\Admin();
        }

        if (isset($this->_links['admin']))
        {
            return $this->_links['admin'];
        }

        return ($this->_links['admin'] = new \WBT\Model\Weibotui\Admin($this->getAdmin()));
    }
}
?>