<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under WBT\Business namespace.
namespace WBT\Model\Weibotui;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class AdminRole extends Model
{
    const ROLE_NAME = 'role_name';
    const DISPLAY_NAME = 'display_name';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'weibotui',
                'admin_role',
                'role_name',
                [
                    'role_name' => ['name' => _META_('weibotui.admin_role.role_name'), 'type' => 'idname', 'required' => true],
                    'display_name' => ['name' => _META_('weibotui.admin_role.display_name'), 'type' => 'text', 'min' => 1, 'max' => 20, 'required' => true],
                ],
                [
                ],
                [
                ],
                [
                    'admin_with_role' => ['role_name', 'role', false, 'admin', 'admin', 'admin_id'],
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets 
     * @return string
     */
    public function getRoleName()
    {
        return $this->__get(self::ROLE_NAME);
    }

    /**
     * Sets 
     * @param string $value
     * @return AdminRole
     */
    public function setRoleName($value)
    {
        $this->__set(self::ROLE_NAME, $value);

        return $this;
    }

    /**
     * Gets 
     * @return string
     */
    public function getDisplayName()
    {
        return $this->__get(self::DISPLAY_NAME);
    }

    /**
     * Sets 
     * @param string $value
     * @return AdminRole
     */
    public function setDisplayName($value)
    {
        $this->__set(self::DISPLAY_NAME, $value);

        return $this;
    }
}
?>