<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under WBT\Business namespace.
namespace WBT\Model\Weibotui;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class City extends Model
{
    const CODE = 'code';
    const _IS_DELETED = '_is_deleted';
    const NAME = 'name';
    const ADMIN_CODE = 'admin_code';
    const POSTCODE = 'postcode';
    const PHONE_AREA_CODE = 'phone_area_code';
    const PROVINCE = 'province';

    const WITH_PROVINCE = 'city.province:province.code';


    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'weibotui',
                'city',
                'code',
                [
                    'code' => ['name' => _META_('weibotui.city.code'), 'type' => 'idname', 'required' => true],
                    '_is_deleted' => ['name' => _META_('weibotui.city._is_deleted'), 'type' => 'bool', 'required' => true, 'db_insert' => true, 'roc' => true, 'rou' => true],
                    'name' => ['name' => _META_('weibotui.city.name'), 'type' => 'text', 'min' => 1, 'max' => 40],
                    'admin_code' => ['name' => _META_('weibotui.city.admin_code'), 'type' => 'idname'],
                    'postcode' => ['name' => _META_('weibotui.city.postcode'), 'type' => 'text', 'min' => 1, 'max' => 10],
                    'phone_area_code' => ['name' => _META_('weibotui.city.phone_area_code'), 'type' => 'int', 'length' => 4],
                    'province' => ['name' => _META_('weibotui.city.province'), 'type' => 'idname', 'required' => true],
                ],
                [
                    'logical_deletion' => '_is_deleted',
                ],
                [
                    'province' => self::WITH_PROVINCE,
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets 编码
     * @return string
     */
    public function getCode()
    {
        return $this->__get(self::CODE);
    }

    /**
     * Sets 编码
     * @param string $value
     * @return City
     */
    public function setCode($value)
    {
        $this->__set(self::CODE, $value);

        return $this;
    }

    /**
     * Gets isdeleted
     * @return bool
     */
    public function getIsDeleted()
    {
        return $this->__get(self::_IS_DELETED);
    }

    /**
     * Sets isdeleted
     * @param bool $value
     * @return City
     */
    public function setIsDeleted($value)
    {
        $this->__set(self::_IS_DELETED, $value);

        return $this;
    }

    /**
     * Gets 名称
     * @return string
     */
    public function getName()
    {
        return $this->__get(self::NAME);
    }

    /**
     * Sets 名称
     * @param string $value
     * @return City
     */
    public function setName($value)
    {
        $this->__set(self::NAME, $value);

        return $this;
    }

    /**
     * Gets 行政区号
     * @return string
     */
    public function getAdminCode()
    {
        return $this->__get(self::ADMIN_CODE);
    }

    /**
     * Sets 行政区号
     * @param string $value
     * @return City
     */
    public function setAdminCode($value)
    {
        $this->__set(self::ADMIN_CODE, $value);

        return $this;
    }

    /**
     * Gets 邮编
     * @return string
     */
    public function getPostcode()
    {
        return $this->__get(self::POSTCODE);
    }

    /**
     * Sets 邮编
     * @param string $value
     * @return City
     */
    public function setPostcode($value)
    {
        $this->__set(self::POSTCODE, $value);

        return $this;
    }

    /**
     * Gets 电话区号
     * @return int
     */
    public function getPhoneAreaCode()
    {
        return $this->__get(self::PHONE_AREA_CODE);
    }

    /**
     * Sets 电话区号
     * @param int $value
     * @return City
     */
    public function setPhoneAreaCode($value)
    {
        $this->__set(self::PHONE_AREA_CODE, $value);

        return $this;
    }

    /**
     * Gets 省
     * @return string
     */
    public function getProvince()
    {
        return $this->__get(self::PROVINCE);
    }

    /**
     * Sets 省
     * @param string $value
     * @return City
     */
    public function setProvince($value)
    {
        $this->__set(self::PROVINCE, $value);

        return $this;
    }

    /**
     * @param bool $new
     * @return \WBT\Model\Weibotui\Province
     */
    public function getProvince_($new = false)
    {
        if ($new)
        {
            return new \WBT\Model\Weibotui\Province();
        }

        if (isset($this->_links['province']))
        {
            return $this->_links['province'];
        }

        return ($this->_links['province'] = new \WBT\Model\Weibotui\Province($this->getProvince()));
    }
}
?>