<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under WBT\Business namespace.
namespace WBT\Model\Weibotui;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class Country extends Model
{
    const CODE = 'code';
    const _IS_DELETED = '_is_deleted';
    const NAME = 'name';
    const PHONE_AREA_CODE = 'phone_area_code';
    const CAPITAL_CITY = 'capital_city';

    const WITH_CAPITAL_CITY = 'country.capital_city:province.code';


    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'weibotui',
                'country',
                'code',
                [
                    'code' => ['name' => _META_('weibotui.country.code'), 'type' => 'idname', 'required' => true],
                    '_is_deleted' => ['name' => _META_('weibotui.country._is_deleted'), 'type' => 'bool', 'required' => true, 'db_insert' => true, 'roc' => true, 'rou' => true],
                    'name' => ['name' => _META_('weibotui.country.name'), 'type' => 'text', 'min' => 1, 'max' => 40],
                    'phone_area_code' => ['name' => _META_('weibotui.country.phone_area_code'), 'type' => 'int', 'length' => 4],
                    'capital_city' => ['name' => _META_('weibotui.country.capital_city'), 'type' => 'idname'],
                ],
                [
                    'logical_deletion' => '_is_deleted',
                ],
                [
                    'capital_city' => self::WITH_CAPITAL_CITY,
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets 编码
     * @return string
     */
    public function getCode()
    {
        return $this->__get(self::CODE);
    }

    /**
     * Sets 编码
     * @param string $value
     * @return Country
     */
    public function setCode($value)
    {
        $this->__set(self::CODE, $value);

        return $this;
    }

    /**
     * Gets isdeleted
     * @return bool
     */
    public function getIsDeleted()
    {
        return $this->__get(self::_IS_DELETED);
    }

    /**
     * Sets isdeleted
     * @param bool $value
     * @return Country
     */
    public function setIsDeleted($value)
    {
        $this->__set(self::_IS_DELETED, $value);

        return $this;
    }

    /**
     * Gets 名称
     * @return string
     */
    public function getName()
    {
        return $this->__get(self::NAME);
    }

    /**
     * Sets 名称
     * @param string $value
     * @return Country
     */
    public function setName($value)
    {
        $this->__set(self::NAME, $value);

        return $this;
    }

    /**
     * Gets 电话区号
     * @return int
     */
    public function getPhoneAreaCode()
    {
        return $this->__get(self::PHONE_AREA_CODE);
    }

    /**
     * Sets 电话区号
     * @param int $value
     * @return Country
     */
    public function setPhoneAreaCode($value)
    {
        $this->__set(self::PHONE_AREA_CODE, $value);

        return $this;
    }

    /**
     * Gets 首都
     * @return string
     */
    public function getCapitalCity()
    {
        return $this->__get(self::CAPITAL_CITY);
    }

    /**
     * Sets 首都
     * @param string $value
     * @return Country
     */
    public function setCapitalCity($value)
    {
        $this->__set(self::CAPITAL_CITY, $value);

        return $this;
    }

    /**
     * @param bool $new
     * @return \WBT\Model\Weibotui\Province
     */
    public function getCapitalCity_($new = false)
    {
        if ($new)
        {
            return new \WBT\Model\Weibotui\Province();
        }

        if (isset($this->_links['capital_city']))
        {
            return $this->_links['capital_city'];
        }

        return ($this->_links['capital_city'] = new \WBT\Model\Weibotui\Province($this->getCapitalCity()));
    }
}
?>