<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace WBT\Model\Weibotui;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class DingshiWeiboStatus implements ValidatorInterface
{
    const TOSEND = 'tosend';
    const SENDING = 'sending';
    const SENTOK = 'sentok';
    const SENTFAILED = 'sentfailed';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::TOSEND => _META_('weibotui.dingshi_weibo_status.tosend'),
                self::SENDING => _META_('weibotui.dingshi_weibo_status.sending'),
                self::SENTOK => _META_('weibotui.dingshi_weibo_status.sentok'),
                self::SENTFAILED => _META_('weibotui.dingshi_weibo_status.sentfailed'),
            );
        }

        return self::$_data;
    }

    public static function getValues()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($value)
    {
        $data = self::getDictionary();
        return $data[$value];
    }

    public static function getDefaultValue()
    {
        return self::TOSEND;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}