<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under WBT\Business namespace.
namespace WBT\Model\Weibotui;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class District extends Model
{
    const CODE = 'code';
    const _IS_DELETED = '_is_deleted';
    const NAME = 'name';
    const ADMIN_CODE = 'admin_code';
    const POSTCODE = 'postcode';
    const CITY = 'city';

    const WITH_CITY = 'district.city:city.code';


    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'weibotui',
                'district',
                'code',
                [
                    'code' => ['name' => _META_('weibotui.district.code'), 'type' => 'idname', 'required' => true],
                    '_is_deleted' => ['name' => _META_('weibotui.district._is_deleted'), 'type' => 'bool', 'required' => true, 'db_insert' => true, 'roc' => true, 'rou' => true],
                    'name' => ['name' => _META_('weibotui.district.name'), 'type' => 'text', 'min' => 1, 'max' => 40],
                    'admin_code' => ['name' => _META_('weibotui.district.admin_code'), 'type' => 'idname'],
                    'postcode' => ['name' => _META_('weibotui.district.postcode'), 'type' => 'text', 'min' => 1, 'max' => 10],
                    'city' => ['name' => _META_('weibotui.district.city'), 'type' => 'idname', 'required' => true],
                ],
                [
                    'logical_deletion' => '_is_deleted',
                ],
                [
                    'city' => self::WITH_CITY,
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets 编码
     * @return string
     */
    public function getCode()
    {
        return $this->__get(self::CODE);
    }

    /**
     * Sets 编码
     * @param string $value
     * @return District
     */
    public function setCode($value)
    {
        $this->__set(self::CODE, $value);

        return $this;
    }

    /**
     * Gets isdeleted
     * @return bool
     */
    public function getIsDeleted()
    {
        return $this->__get(self::_IS_DELETED);
    }

    /**
     * Sets isdeleted
     * @param bool $value
     * @return District
     */
    public function setIsDeleted($value)
    {
        $this->__set(self::_IS_DELETED, $value);

        return $this;
    }

    /**
     * Gets 名称
     * @return string
     */
    public function getName()
    {
        return $this->__get(self::NAME);
    }

    /**
     * Sets 名称
     * @param string $value
     * @return District
     */
    public function setName($value)
    {
        $this->__set(self::NAME, $value);

        return $this;
    }

    /**
     * Gets 行政区号
     * @return string
     */
    public function getAdminCode()
    {
        return $this->__get(self::ADMIN_CODE);
    }

    /**
     * Sets 行政区号
     * @param string $value
     * @return District
     */
    public function setAdminCode($value)
    {
        $this->__set(self::ADMIN_CODE, $value);

        return $this;
    }

    /**
     * Gets 邮编
     * @return string
     */
    public function getPostcode()
    {
        return $this->__get(self::POSTCODE);
    }

    /**
     * Sets 邮编
     * @param string $value
     * @return District
     */
    public function setPostcode($value)
    {
        $this->__set(self::POSTCODE, $value);

        return $this;
    }

    /**
     * Gets 市
     * @return string
     */
    public function getCity()
    {
        return $this->__get(self::CITY);
    }

    /**
     * Sets 市
     * @param string $value
     * @return District
     */
    public function setCity($value)
    {
        $this->__set(self::CITY, $value);

        return $this;
    }

    /**
     * @param bool $new
     * @return \WBT\Model\Weibotui\City
     */
    public function getCity_($new = false)
    {
        if ($new)
        {
            return new \WBT\Model\Weibotui\City();
        }

        if (isset($this->_links['city']))
        {
            return $this->_links['city'];
        }

        return ($this->_links['city'] = new \WBT\Model\Weibotui\City($this->getCity()));
    }
}
?>