<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace WBT\Model\Weibotui;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class IncomeType implements ValidatorInterface
{
    const ADVERTISER_DEPOSIT = 'advertiser_deposit';
    const CHANGWEIBO_DEPOSIT = 'changweibo_deposit';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::ADVERTISER_DEPOSIT => _META_('weibotui.income_type.advertiser_deposit'),
                self::CHANGWEIBO_DEPOSIT => _META_('weibotui.income_type.changweibo_deposit'),
            );
        }

        return self::$_data;
    }

    public static function getValues()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($value)
    {
        $data = self::getDictionary();
        return $data[$value];
    }

    public static function getDefaultValue()
    {
        return self::ADVERTISER_DEPOSIT;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}