<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace WBT\Model\Weibotui;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class InventoryStatus implements ValidatorInterface
{
    const UNAUDIT = 'unaudit';
    const AUDIT_FAILED = 'audit_failed';
    const AVAILABLE = 'available';
    const UNAVAILABLE = 'unavailable';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::UNAUDIT => _META_('weibotui.inventory_status.unaudit'),
                self::AUDIT_FAILED => _META_('weibotui.inventory_status.audit_failed'),
                self::AVAILABLE => _META_('weibotui.inventory_status.available'),
                self::UNAVAILABLE => _META_('weibotui.inventory_status.unavailable'),
            );
        }

        return self::$_data;
    }

    public static function getStates()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($state)
    {
        $data = self::getDictionary();
        return $data[$state];
    }

    public static function getDefaultValue()
    {
        return self::UNAUDIT;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}