<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under WBT\Business namespace.
namespace WBT\Model\Weibotui;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class Invoice extends Model
{
    const INVOICE_ID = 'invoice_id';
    const _CREATED_AT = '_created_at';
    const INVOICE_NO = 'invoice_no';
    const TITLE = 'title';
    const ISSUED_DATE = 'issued_date';
    const TOTAL_AMOUNT = 'total_amount';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'weibotui',
                'invoice',
                'invoice_id',
                [
                    'invoice_id' => ['name' => _META_('weibotui.invoice.invoice_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    '_created_at' => ['name' => _META_('weibotui.invoice._created_at'), 'type' => 'timestamp', 'required' => true, 'default' => new DbExpr('NOW()'), 'roc' => true, 'rou' => true],
                    'invoice_no' => ['name' => _META_('weibotui.invoice.invoice_no'), 'type' => 'digits', 'length' => 10, 'required' => true],
                    'title' => ['name' => _META_('weibotui.invoice.title'), 'type' => 'text', 'length' => 100, 'required' => true],
                    'issued_date' => ['name' => _META_('weibotui.invoice.issued_date'), 'type' => 'date', 'required' => true],
                    'total_amount' => ['name' => _META_('weibotui.invoice.total_amount'), 'type' => 'money', 'precision' => 2, 'required' => true],
                ],
                [
                    'auto_increment_id' => 'invoice_id',
                    'create_timestamp' => '_created_at',
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getInvoiceID()
    {
        return $this->__get(self::INVOICE_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return Invoice
     */
    public function setInvoiceID($value)
    {
        $this->__set(self::INVOICE_ID, $value);

        return $this;
    }

    /**
     * Gets createdat
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->__get(self::_CREATED_AT);
    }

    /**
     * Sets createdat
     * @param string $value
     * @return Invoice
     */
    public function setCreatedAt($value)
    {
        $this->__set(self::_CREATED_AT, $value);

        return $this;
    }

    /**
     * Gets 发票号码
     * @return string
     */
    public function getInvoiceNo()
    {
        return $this->__get(self::INVOICE_NO);
    }

    /**
     * Sets 发票号码
     * @param string $value
     * @return Invoice
     */
    public function setInvoiceNo($value)
    {
        $this->__set(self::INVOICE_NO, $value);

        return $this;
    }

    /**
     * Gets 发票抬头
     * @return string
     */
    public function getTitle()
    {
        return $this->__get(self::TITLE);
    }

    /**
     * Sets 发票抬头
     * @param string $value
     * @return Invoice
     */
    public function setTitle($value)
    {
        $this->__set(self::TITLE, $value);

        return $this;
    }

    /**
     * Gets 开票日期
     * @return string
     */
    public function getIssuedDate()
    {
        return $this->__get(self::ISSUED_DATE);
    }

    /**
     * Sets 开票日期
     * @param string $value
     * @return Invoice
     */
    public function setIssuedDate($value)
    {
        $this->__set(self::ISSUED_DATE, $value);

        return $this;
    }

    /**
     * Gets 总金额
     * @return float
     */
    public function getTotalAmount()
    {
        return $this->__get(self::TOTAL_AMOUNT);
    }

    /**
     * Sets 总金额
     * @param float $value
     * @return Invoice
     */
    public function setTotalAmount($value)
    {
        $this->__set(self::TOTAL_AMOUNT, $value);

        return $this;
    }
}
?>