<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace WBT\Model\Weibotui;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class OAuthClientLevel implements ValidatorInterface
{
    const PUBLIC_CLIENT = 'public_client';
    const PRIVATE_CLIENT = 'private_client';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::PUBLIC_CLIENT => _META_('weibotui.oauth_client_level.public_client'),
                self::PRIVATE_CLIENT => _META_('weibotui.oauth_client_level.private_client'),
            );
        }

        return self::$_data;
    }

    public static function getValues()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($value)
    {
        $data = self::getDictionary();
        return $data[$value];
    }

    public static function getDefaultValue()
    {
        return self::PUBLIC_CLIENT;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}