<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under WBT\Business namespace.
namespace WBT\Model\Weibotui;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class QQDingshiWeibo extends Model
{
    const QQ_DINGSHI_WEIBO_ID = 'qq_dingshi_weibo_id';
    const _CREATED_AT = '_created_at';
    const _UPDATED_AT = '_updated_at';
    const UID = 'uid';
    const APP_KEY = 'app_key';
    const TEXT = 'text';
    const IMAGE_URL = 'image_url';
    const RT_ID = 'rt_id';
    const RT_JSON = 'rt_json';
    const SEND_TIME = 'send_time';
    const WEIBO_URL = 'weibo_url';
    const IP_ADDRESS = 'ip_address';
    const ERRNO = 'errno';
    const ERROR = 'error';
    const STATUS = 'status';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'weibotui',
                'qq_dingshi_weibo',
                'qq_dingshi_weibo_id',
                [
                    'qq_dingshi_weibo_id' => ['name' => _META_('weibotui.qq_dingshi_weibo.qq_dingshi_weibo_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    '_created_at' => ['name' => _META_('weibotui.qq_dingshi_weibo._created_at'), 'type' => 'timestamp', 'required' => true, 'default' => new DbExpr('NOW()'), 'roc' => true, 'rou' => true],
                    '_updated_at' => ['name' => _META_('weibotui.qq_dingshi_weibo._updated_at'), 'type' => 'timestamp', 'required' => true, 'db_insert' => true, 'roc' => true, 'rou' => true],
                    'uid' => ['name' => _META_('weibotui.qq_dingshi_weibo.uid'), 'type' => 'text', 'length' => 64, 'required' => true],
                    'app_key' => ['name' => _META_('weibotui.qq_dingshi_weibo.app_key'), 'type' => 'text', 'length' => 20, 'required' => true],
                    'text' => ['name' => _META_('weibotui.qq_dingshi_weibo.text'), 'type' => 'text', 'max' => 1024, 'required' => true],
                    'image_url' => ['name' => _META_('weibotui.qq_dingshi_weibo.image_url'), 'type' => 'url'],
                    'rt_id' => ['name' => _META_('weibotui.qq_dingshi_weibo.rt_id'), 'type' => 'int', 'length' => 20, 'db_insert' => true, 'required' => true],
                    'rt_json' => ['name' => _META_('weibotui.qq_dingshi_weibo.rt_json'), 'type' => 'text', 'max' => 5120],
                    'send_time' => ['name' => _META_('weibotui.qq_dingshi_weibo.send_time'), 'type' => 'datetime', 'required' => true],
                    'weibo_url' => ['name' => _META_('weibotui.qq_dingshi_weibo.weibo_url'), 'type' => 'text', 'length' => 64],
                    'ip_address' => ['name' => _META_('weibotui.qq_dingshi_weibo.ip_address'), 'type' => 'ipv4', 'default' => new \Bluefin\Data\Functor\VarTextProvider("{{gateway.client_ip}}")],
                    'errno' => ['name' => _META_('weibotui.qq_dingshi_weibo.errno'), 'type' => 'int', 'db_insert' => true, 'required' => true],
                    'error' => ['name' => _META_('weibotui.qq_dingshi_weibo.error'), 'type' => 'text', 'max' => 256],
                    'status' => ['name' => _META_('weibotui.qq_dingshi_weibo.status'), 'type' => 'text', 'max' => 20, 'required' => true, 'enum' => new DingshiWeiboStatus(), 'db_insert' => true],
                ],
                [
                    'auto_increment_id' => 'qq_dingshi_weibo_id',
                    'create_timestamp' => '_created_at',
                    'update_timestamp' => '_updated_at',
                    'unique_keys' => [['uid', 'send_time']],
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getQQDingshiWeiboID()
    {
        return $this->__get(self::QQ_DINGSHI_WEIBO_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return QQDingshiWeibo
     */
    public function setQQDingshiWeiboID($value)
    {
        $this->__set(self::QQ_DINGSHI_WEIBO_ID, $value);

        return $this;
    }

    /**
     * Gets createdat
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->__get(self::_CREATED_AT);
    }

    /**
     * Sets createdat
     * @param string $value
     * @return QQDingshiWeibo
     */
    public function setCreatedAt($value)
    {
        $this->__set(self::_CREATED_AT, $value);

        return $this;
    }

    /**
     * Gets updatedat
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->__get(self::_UPDATED_AT);
    }

    /**
     * Sets updatedat
     * @param string $value
     * @return QQDingshiWeibo
     */
    public function setUpdatedAt($value)
    {
        $this->__set(self::_UPDATED_AT, $value);

        return $this;
    }

    /**
     * Gets weibo user id
     * @return string
     */
    public function getUID()
    {
        return $this->__get(self::UID);
    }

    /**
     * Sets weibo user id
     * @param string $value
     * @return QQDingshiWeibo
     */
    public function setUID($value)
    {
        $this->__set(self::UID, $value);

        return $this;
    }

    /**
     * Gets app key
     * @return string
     */
    public function getAppKey()
    {
        return $this->__get(self::APP_KEY);
    }

    /**
     * Sets app key
     * @param string $value
     * @return QQDingshiWeibo
     */
    public function setAppKey($value)
    {
        $this->__set(self::APP_KEY, $value);

        return $this;
    }

    /**
     * Gets 微博文本内容
     * @return string
     */
    public function getText()
    {
        return $this->__get(self::TEXT);
    }

    /**
     * Sets 微博文本内容
     * @param string $value
     * @return QQDingshiWeibo
     */
    public function setText($value)
    {
        $this->__set(self::TEXT, $value);

        return $this;
    }

    /**
     * Gets 图片url
     * @return string
     */
    public function getImageUrl()
    {
        return $this->__get(self::IMAGE_URL);
    }

    /**
     * Sets 图片url
     * @param string $value
     * @return QQDingshiWeibo
     */
    public function setImageUrl($value)
    {
        $this->__set(self::IMAGE_URL, $value);

        return $this;
    }

    /**
     * Gets 要转发的微博id
     * @return int
     */
    public function getRtID()
    {
        return $this->__get(self::RT_ID);
    }

    /**
     * Sets 要转发的微博id
     * @param int $value
     * @return QQDingshiWeibo
     */
    public function setRtID($value)
    {
        $this->__set(self::RT_ID, $value);

        return $this;
    }

    /**
     * Gets 微要转发微博的json内容
     * @return string
     */
    public function getRtJson()
    {
        return $this->__get(self::RT_JSON);
    }

    /**
     * Sets 微要转发微博的json内容
     * @param string $value
     * @return QQDingshiWeibo
     */
    public function setRtJson($value)
    {
        $this->__set(self::RT_JSON, $value);

        return $this;
    }

    /**
     * Gets 发送时间
     * @return string
     */
    public function getSendTime()
    {
        return $this->__get(self::SEND_TIME);
    }

    /**
     * Sets 发送时间
     * @param string $value
     * @return QQDingshiWeibo
     */
    public function setSendTime($value)
    {
        $this->__set(self::SEND_TIME, $value);

        return $this;
    }

    /**
     * Gets 微博url地址
     * @return string
     */
    public function getWeiboUrl()
    {
        return $this->__get(self::WEIBO_URL);
    }

    /**
     * Sets 微博url地址
     * @param string $value
     * @return QQDingshiWeibo
     */
    public function setWeiboUrl($value)
    {
        $this->__set(self::WEIBO_URL, $value);

        return $this;
    }

    /**
     * Gets 登录地址
     * @return string
     */
    public function getIPAddress()
    {
        return $this->__get(self::IP_ADDRESS);
    }

    /**
     * Sets 登录地址
     * @param string $value
     * @return QQDingshiWeibo
     */
    public function setIPAddress($value)
    {
        $this->__set(self::IP_ADDRESS, $value);

        return $this;
    }

    /**
     * Gets 错误号。非0值标志有错误
     * @return int
     */
    public function getErrno()
    {
        return $this->__get(self::ERRNO);
    }

    /**
     * Sets 错误号。非0值标志有错误
     * @param int $value
     * @return QQDingshiWeibo
     */
    public function setErrno($value)
    {
        $this->__set(self::ERRNO, $value);

        return $this;
    }

    /**
     * Gets 错误信息
     * @return string
     */
    public function getError()
    {
        return $this->__get(self::ERROR);
    }

    /**
     * Sets 错误信息
     * @param string $value
     * @return QQDingshiWeibo
     */
    public function setError($value)
    {
        $this->__set(self::ERROR, $value);

        return $this;
    }

    /**
     * Gets 发送状态
     * @return string
     */
    public function getStatus()
    {
        return $this->__get(self::STATUS);
    }

    /**
     * Gets 发送状态 display name
     * @return string
     */
    public function getStatus_EnumValue()
    {
        $option = $this->metadata()->getFilterOption('status');
        return $option['enum']::getDisplayName($this->__get(self::STATUS));
    }

    /**
     * Sets 发送状态
     * @param string $value
     * @return QQDingshiWeibo
     */
    public function setStatus($value)
    {
        $this->__set(self::STATUS, $value);

        return $this;
    }
}
?>