<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under WBT\Business namespace.
namespace WBT\Model\Weibotui;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class StaffInCorporate extends Model
{
    const STAFF_IN_CORPORATE_ID = 'staff_in_corporate_id';
    const _CREATED_AT = '_created_at';
    const USER = 'user';
    const COMPANY = 'company';

    const WITH_USER = 'staff_in_corporate.user:user.user_id';
    const WITH_COMPANY = 'staff_in_corporate.company:corporate.corporate_id';


    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'weibotui',
                'staff_in_corporate',
                'staff_in_corporate_id',
                [
                    'staff_in_corporate_id' => ['name' => _META_('weibotui.staff_in_corporate.staff_in_corporate_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    '_created_at' => ['name' => _META_('weibotui.staff_in_corporate._created_at'), 'type' => 'timestamp', 'required' => true, 'default' => new DbExpr('NOW()'), 'roc' => true, 'rou' => true],
                    'user' => ['name' => _META_('weibotui.staff_in_corporate.user'), 'type' => 'int', 'length' => 10, 'min' => 100000, 'required' => true],
                    'company' => ['name' => _META_('weibotui.staff_in_corporate.company'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true],
                ],
                [
                    'auto_increment_id' => 'staff_in_corporate_id',
                    'create_timestamp' => '_created_at',
                    'unique_keys' => [['user', 'company']],
                ],
                [
                    'user' => self::WITH_USER,
                    'company' => self::WITH_COMPANY,
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getStaffInCorporateID()
    {
        return $this->__get(self::STAFF_IN_CORPORATE_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return StaffInCorporate
     */
    public function setStaffInCorporateID($value)
    {
        $this->__set(self::STAFF_IN_CORPORATE_ID, $value);

        return $this;
    }

    /**
     * Gets createdat
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->__get(self::_CREATED_AT);
    }

    /**
     * Sets createdat
     * @param string $value
     * @return StaffInCorporate
     */
    public function setCreatedAt($value)
    {
        $this->__set(self::_CREATED_AT, $value);

        return $this;
    }

    /**
     * Gets 用户
     * @return int
     */
    public function getUser()
    {
        return $this->__get(self::USER);
    }

    /**
     * Sets 用户
     * @param int $value
     * @return StaffInCorporate
     */
    public function setUser($value)
    {
        $this->__set(self::USER, $value);

        return $this;
    }

    /**
     * Gets 企业
     * @return int
     */
    public function getCompany()
    {
        return $this->__get(self::COMPANY);
    }

    /**
     * Sets 企业
     * @param int $value
     * @return StaffInCorporate
     */
    public function setCompany($value)
    {
        $this->__set(self::COMPANY, $value);

        return $this;
    }

    /**
     * @param bool $new
     * @return \WBT\Model\Weibotui\User
     */
    public function getUser_($new = false)
    {
        if ($new)
        {
            return new \WBT\Model\Weibotui\User();
        }

        if (isset($this->_links['user']))
        {
            return $this->_links['user'];
        }

        return ($this->_links['user'] = new \WBT\Model\Weibotui\User($this->getUser()));
    }

    /**
     * @param bool $new
     * @return \WBT\Model\Weibotui\Corporate
     */
    public function getCompany_($new = false)
    {
        if ($new)
        {
            return new \WBT\Model\Weibotui\Corporate();
        }

        if (isset($this->_links['company']))
        {
            return $this->_links['company'];
        }

        return ($this->_links['company'] = new \WBT\Model\Weibotui\Corporate($this->getCompany()));
    }
}
?>