<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under WBT\Business namespace.
namespace WBT\Model\Weibotui;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class SystemProperty extends Model
{
    const _UPDATED_AT = '_updated_at';
    const NAME = 'name';
    const VALUE = 'value';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'weibotui',
                'system_property',
                'name',
                [
                    '_updated_at' => ['name' => _META_('weibotui.system_property._updated_at'), 'type' => 'timestamp', 'required' => true, 'db_insert' => true, 'roc' => true, 'rou' => true],
                    'name' => ['name' => _META_('weibotui.system_property.name'), 'type' => 'text', 'min' => 1, 'max' => 40],
                    'value' => ['name' => _META_('weibotui.system_property.value'), 'type' => 'text', 'required' => true],
                ],
                [
                    'update_timestamp' => '_updated_at',
                    'key_value_cache' => 'value',
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets updatedat
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->__get(self::_UPDATED_AT);
    }

    /**
     * Sets updatedat
     * @param string $value
     * @return SystemProperty
     */
    public function setUpdatedAt($value)
    {
        $this->__set(self::_UPDATED_AT, $value);

        return $this;
    }

    /**
     * Gets 名称
     * @return string
     */
    public function getName()
    {
        return $this->__get(self::NAME);
    }

    /**
     * Sets 名称
     * @param string $value
     * @return SystemProperty
     */
    public function setName($value)
    {
        $this->__set(self::NAME, $value);

        return $this;
    }

    /**
     * Gets 属性值
     * @return string
     */
    public function getValue()
    {
        return $this->__get(self::VALUE);
    }

    /**
     * Sets 属性值
     * @param string $value
     * @return SystemProperty
     */
    public function setValue($value)
    {
        $this->__set(self::VALUE, $value);

        return $this;
    }
}
?>