<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under WBT\Business namespace.
namespace WBT\Model\Weibotui;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class TopicCategory extends Model
{
    const CODE = 'code';
    const NAME = 'name';
    const _IS_DELETED = '_is_deleted';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'weibotui',
                'topic_category',
                'code',
                [
                    'code' => ['name' => _META_('weibotui.topic_category.code'), 'type' => 'idname', 'required' => true],
                    'name' => ['name' => _META_('weibotui.topic_category.name'), 'type' => 'text', 'min' => 1, 'max' => 40, 'required' => true],
                    '_is_deleted' => ['name' => _META_('weibotui.topic_category._is_deleted'), 'type' => 'bool', 'required' => true, 'db_insert' => true, 'roc' => true, 'rou' => true],
                ],
                [
                    'logical_deletion' => '_is_deleted',
                ],
                [
                ],
                [
                    'weibo_topic' => ['code', 'catetory', false, 'weibo', 'weibo', 'weibo_id'],
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets 编码
     * @return string
     */
    public function getCode()
    {
        return $this->__get(self::CODE);
    }

    /**
     * Sets 编码
     * @param string $value
     * @return TopicCategory
     */
    public function setCode($value)
    {
        $this->__set(self::CODE, $value);

        return $this;
    }

    /**
     * Gets 名称
     * @return string
     */
    public function getName()
    {
        return $this->__get(self::NAME);
    }

    /**
     * Sets 名称
     * @param string $value
     * @return TopicCategory
     */
    public function setName($value)
    {
        $this->__set(self::NAME, $value);

        return $this;
    }

    /**
     * Gets isdeleted
     * @return bool
     */
    public function getIsDeleted()
    {
        return $this->__get(self::_IS_DELETED);
    }

    /**
     * Sets isdeleted
     * @param bool $value
     * @return TopicCategory
     */
    public function setIsDeleted($value)
    {
        $this->__set(self::_IS_DELETED, $value);

        return $this;
    }
}
?>