<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace WBT\Model\Weibotui;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class TransactionStatus implements ValidatorInterface
{
    const ONGOING = 'ongoing';
    const DONE = 'done';
    const FAILED = 'failed';
    const CANCELLED = 'cancelled';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::ONGOING => _META_('weibotui.transaction_status.ongoing'),
                self::DONE => _META_('weibotui.transaction_status.done'),
                self::FAILED => _META_('weibotui.transaction_status.failed'),
                self::CANCELLED => _META_('weibotui.transaction_status.cancelled'),
            );
        }

        return self::$_data;
    }

    public static function getStates()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($state)
    {
        $data = self::getDictionary();
        return $data[$state];
    }

    public static function getDefaultValue()
    {
        return self::ONGOING;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}