<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace WBT\Model\Weibotui;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class TuikeStatus implements ValidatorInterface
{
    const UNVERIFIED = 'unverified';
    const WAIT_VERIFY = 'wait_verify';
    const VERIFIED = 'verified';
    const VERIFY_FAILED = 'verify_failed';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::UNVERIFIED => _META_('weibotui.tuike_status.unverified'),
                self::WAIT_VERIFY => _META_('weibotui.tuike_status.wait_verify'),
                self::VERIFIED => _META_('weibotui.tuike_status.verified'),
                self::VERIFY_FAILED => _META_('weibotui.tuike_status.verify_failed'),
            );
        }

        return self::$_data;
    }

    public static function getStates()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($state)
    {
        $data = self::getDictionary();
        return $data[$state];
    }

    public static function getDefaultValue()
    {
        return self::UNVERIFIED;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}