<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace WBT\Model\Weibotui;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class UserExpenseStatus implements ValidatorInterface
{
    const PENDING = 'pending';
    const PAID = 'paid';
    const CANCELLED = 'cancelled';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::PENDING => _META_('weibotui.user_expense_status.pending'),
                self::PAID => _META_('weibotui.user_expense_status.paid'),
                self::CANCELLED => _META_('weibotui.user_expense_status.cancelled'),
            );
        }

        return self::$_data;
    }

    public static function getStates()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($state)
    {
        $data = self::getDictionary();
        return $data[$state];
    }

    public static function getDefaultValue()
    {
        return self::PENDING;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}