<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace WBT\Model\Weibotui;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class UserRole implements ValidatorInterface
{
    const SN_USER = 'sn_user';
    const TUIKE = 'tuike';
    const ADVERTISER = 'advertiser';
    const STAFF = 'staff';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::SN_USER => _META_('weibotui.user_role.sn_user'),
                self::TUIKE => _META_('weibotui.user_role.tuike'),
                self::ADVERTISER => _META_('weibotui.user_role.advertiser'),
                self::STAFF => _META_('weibotui.user_role.staff'),
            );
        }

        return self::$_data;
    }

    public static function getValues()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($value)
    {
        $data = self::getDictionary();
        return $data[$value];
    }

    public static function getDefaultValue()
    {
        return self::SN_USER;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}