<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace WBT\Model\Weibotui;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class UserStatus implements ValidatorInterface
{
    const NONACTIVATED = 'nonactivated';
    const ACTIVATED = 'activated';
    const DISABLED = 'disabled';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::NONACTIVATED => _META_('weibotui.user_status.nonactivated'),
                self::ACTIVATED => _META_('weibotui.user_status.activated'),
                self::DISABLED => _META_('weibotui.user_status.disabled'),
            );
        }

        return self::$_data;
    }

    public static function getStates()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($state)
    {
        $data = self::getDictionary();
        return $data[$state];
    }

    public static function getDefaultValue()
    {
        return self::NONACTIVATED;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}