<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace WBT\Model\Weibotui;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class UserBusinessType implements ValidatorInterface
{
    const WEIBO_ORDER = 'weibo_order';
    const CHANG_WEIBO = 'chang_weibo';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::WEIBO_ORDER => _META_('weibotui.user_business_type.weibo_order'),
                self::CHANG_WEIBO => _META_('weibotui.user_business_type.chang_weibo'),
            );
        }

        return self::$_data;
    }

    public static function getValues()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($value)
    {
        $data = self::getDictionary();
        return $data[$value];
    }

    public static function getDefaultValue()
    {
        return self::WEIBO_ORDER;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}