<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under WBT\Business namespace.
namespace WBT\Model\Weibotui;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class UserAsset extends Model
{
    const _CREATED_AT = '_created_at';
    const _UPDATED_AT = '_updated_at';
    const DEPOSIT_BALANCE = 'deposit_balance';
    const INCOME_BALANCE = 'income_balance';
    const POINTS = 'points';
    const USER = 'user';

    const WITH_USER = 'user_asset.user:user.user_id';


    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'weibotui',
                'user_asset',
                'user',
                [
                    '_created_at' => ['name' => _META_('weibotui.user_asset._created_at'), 'type' => 'timestamp', 'required' => true, 'default' => new DbExpr('NOW()'), 'roc' => true, 'rou' => true],
                    '_updated_at' => ['name' => _META_('weibotui.user_asset._updated_at'), 'type' => 'timestamp', 'required' => true, 'db_insert' => true, 'roc' => true, 'rou' => true],
                    'deposit_balance' => ['name' => _META_('weibotui.user_asset.deposit_balance'), 'type' => 'money', 'db_insert' => true, 'precision' => 2, 'required' => true],
                    'income_balance' => ['name' => _META_('weibotui.user_asset.income_balance'), 'type' => 'money', 'db_insert' => true, 'precision' => 2, 'required' => true],
                    'points' => ['name' => _META_('weibotui.user_asset.points'), 'type' => 'int', 'db_insert' => true, 'required' => true],
                    'user' => ['name' => _META_('weibotui.user_asset.user'), 'type' => 'int', 'length' => 10, 'min' => 100000, 'required' => true],
                ],
                [
                    'create_timestamp' => '_created_at',
                    'update_timestamp' => '_updated_at',
                ],
                [
                    'user' => self::WITH_USER,
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets createdat
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->__get(self::_CREATED_AT);
    }

    /**
     * Sets createdat
     * @param string $value
     * @return UserAsset
     */
    public function setCreatedAt($value)
    {
        $this->__set(self::_CREATED_AT, $value);

        return $this;
    }

    /**
     * Gets updatedat
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->__get(self::_UPDATED_AT);
    }

    /**
     * Sets updatedat
     * @param string $value
     * @return UserAsset
     */
    public function setUpdatedAt($value)
    {
        $this->__set(self::_UPDATED_AT, $value);

        return $this;
    }

    /**
     * Gets 储值余额
     * @return float
     */
    public function getDepositBalance()
    {
        return $this->__get(self::DEPOSIT_BALANCE);
    }

    /**
     * Sets 储值余额
     * @param float $value
     * @return UserAsset
     */
    public function setDepositBalance($value)
    {
        $this->__set(self::DEPOSIT_BALANCE, $value);

        return $this;
    }

    /**
     * Gets 收入余额
     * @return float
     */
    public function getIncomeBalance()
    {
        return $this->__get(self::INCOME_BALANCE);
    }

    /**
     * Sets 收入余额
     * @param float $value
     * @return UserAsset
     */
    public function setIncomeBalance($value)
    {
        $this->__set(self::INCOME_BALANCE, $value);

        return $this;
    }

    /**
     * Gets 积分
     * @return int
     */
    public function getPoints()
    {
        return $this->__get(self::POINTS);
    }

    /**
     * Sets 积分
     * @param int $value
     * @return UserAsset
     */
    public function setPoints($value)
    {
        $this->__set(self::POINTS, $value);

        return $this;
    }

    /**
     * Gets 用户
     * @return int
     */
    public function getUser()
    {
        return $this->__get(self::USER);
    }

    /**
     * Sets 用户
     * @param int $value
     * @return UserAsset
     */
    public function setUser($value)
    {
        $this->__set(self::USER, $value);

        return $this;
    }

    /**
     * @param bool $new
     * @return \WBT\Model\Weibotui\User
     */
    public function getUser_($new = false)
    {
        if ($new)
        {
            return new \WBT\Model\Weibotui\User();
        }

        if (isset($this->_links['user']))
        {
            return $this->_links['user'];
        }

        return ($this->_links['user'] = new \WBT\Model\Weibotui\User($this->getUser()));
    }
}
?>