<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace WBT\Model\Weibotui;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class WeiboCampaignStatus implements ValidatorInterface
{
    const UNPUBLISHED = 'unpublished';
    const PUBLISHED = 'published';
    const CLOSED = 'closed';
    const DELETED = 'deleted';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::UNPUBLISHED => _META_('weibotui.weibo_campaign_status.unpublished'),
                self::PUBLISHED => _META_('weibotui.weibo_campaign_status.published'),
                self::CLOSED => _META_('weibotui.weibo_campaign_status.closed'),
                self::DELETED => _META_('weibotui.weibo_campaign_status.deleted'),
            );
        }

        return self::$_data;
    }

    public static function getStates()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($state)
    {
        $data = self::getDictionary();
        return $data[$state];
    }

    public static function getDefaultValue()
    {
        return self::UNPUBLISHED;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}