<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under WBT\Business namespace.
namespace WBT\Model\Weibotui;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class WeiboLoginRecord extends Model
{
    const WEIBO_LOGIN_RECORD_ID = 'weibo_login_record_id';
    const _CREATED_AT = '_created_at';
    const IP_ADDRESS = 'ip_address';
    const WEIBO = 'weibo';

    const WITH_WEIBO = 'weibo_login_record.weibo:weibo.weibo_id';


    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'weibotui',
                'weibo_login_record',
                'weibo_login_record_id',
                [
                    'weibo_login_record_id' => ['name' => _META_('weibotui.weibo_login_record.weibo_login_record_id'), 'type' => 'uuid', 'default' => new \Bluefin\Data\Functor\AutoUUID(), 'required' => true, 'rou' => true],
                    '_created_at' => ['name' => _META_('weibotui.weibo_login_record._created_at'), 'type' => 'timestamp', 'required' => true, 'default' => new DbExpr('NOW()'), 'roc' => true, 'rou' => true],
                    'ip_address' => ['name' => _META_('weibotui.weibo_login_record.ip_address'), 'type' => 'ipv4', 'default' => new \Bluefin\Data\Functor\VarTextProvider("{{gateway.client_ip}}"), 'required' => true],
                    'weibo' => ['name' => _META_('weibotui.weibo_login_record.weibo'), 'type' => 'uuid', 'required' => true],
                ],
                [
                    'auto_uuid' => 'weibo_login_record_id',
                    'create_timestamp' => '_created_at',
                ],
                [
                    'weibo' => self::WITH_WEIBO,
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets uuid
     * @return string
     */
    public function getWeiboLoginRecordID()
    {
        return $this->__get(self::WEIBO_LOGIN_RECORD_ID);
    }

    /**
     * Sets uuid
     * @param string $value
     * @return WeiboLoginRecord
     */
    public function setWeiboLoginRecordID($value)
    {
        $this->__set(self::WEIBO_LOGIN_RECORD_ID, $value);

        return $this;
    }

    /**
     * Gets createdat
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->__get(self::_CREATED_AT);
    }

    /**
     * Sets createdat
     * @param string $value
     * @return WeiboLoginRecord
     */
    public function setCreatedAt($value)
    {
        $this->__set(self::_CREATED_AT, $value);

        return $this;
    }

    /**
     * Gets 登录地址
     * @return string
     */
    public function getIPAddress()
    {
        return $this->__get(self::IP_ADDRESS);
    }

    /**
     * Sets 登录地址
     * @param string $value
     * @return WeiboLoginRecord
     */
    public function setIPAddress($value)
    {
        $this->__set(self::IP_ADDRESS, $value);

        return $this;
    }

    /**
     * Gets 微博账号
     * @return string
     */
    public function getWeibo()
    {
        return $this->__get(self::WEIBO);
    }

    /**
     * Sets 微博账号
     * @param string $value
     * @return WeiboLoginRecord
     */
    public function setWeibo($value)
    {
        $this->__set(self::WEIBO, $value);

        return $this;
    }

    /**
     * @param bool $new
     * @return \WBT\Model\Weibotui\Weibo
     */
    public function getWeibo_($new = false)
    {
        if ($new)
        {
            return new \WBT\Model\Weibotui\Weibo();
        }

        if (isset($this->_links['weibo']))
        {
            return $this->_links['weibo'];
        }

        return ($this->_links['weibo'] = new \WBT\Model\Weibotui\Weibo($this->getWeibo()));
    }
}
?>