<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace WBT\Model\Weibotui;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class WeiboOrderSendMethod implements ValidatorInterface
{
    const DIRECT = 'direct';
    const SCHEDULE = 'schedule';
    const MANUAL = 'manual';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::DIRECT => _META_('weibotui.weibo_order_send_method.direct'),
                self::SCHEDULE => _META_('weibotui.weibo_order_send_method.schedule'),
                self::MANUAL => _META_('weibotui.weibo_order_send_method.manual'),
            );
        }

        return self::$_data;
    }

    public static function getValues()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($value)
    {
        $data = self::getDictionary();
        return $data[$value];
    }

    public static function getDefaultValue()
    {
        return self::DIRECT;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}