<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.5.2 setup script
 * Date: Tue, 10 Jul 2012 17:25:32 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: kc_ppe [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'mysql';
$cfg['Servers'][$i]['host'] = '__MYSQL_HOST__';
$cfg['Servers'][$i]['port'] = '__MYSQL_PORT__';
$cfg['Servers'][$i]['socket'] = '__MYSQL_SOCK__';
$cfg['Servers'][$i]['connect_type'] = 'socket';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '4ffc62d1eb0d57.42419433';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
