-- TABLE personal_profile

CREATE TABLE IF NOT EXISTS `personal_profile` (
    `personal_profile_id` BINARY(16) NOT NULL COMMENT 'UUID',
    `_updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'UpdatedAt',
    `_is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'IsDeleted',
    `first_name` VARCHAR(20) COMMENT '名',
    `last_name` VARCHAR(20) COMMENT '姓',
    `display_name` VARCHAR(40) COMMENT '姓名',
    `nick_name` VARCHAR(20) COMMENT '昵称',
    `photo` VARCHAR(255) COMMENT '相片',
    `avatar` VARCHAR(255) COMMENT '头像',
    `email` VARCHAR(320) COMMENT '邮件地址',
    `email_verified` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '邮件地址验证',
    `id_no` VARCHAR(20) COMMENT '身份证',
    `birthday` DATE COMMENT '生日',
    `mobile` VARCHAR(20) COMMENT '手机',
    `mobile_verified` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '手机验证',
    `home_phone` VARCHAR(20) COMMENT '家庭电话',
    `office_phone` VARCHAR(20) COMMENT '办公电话',
    `homepage` VARCHAR(2083) COMMENT '个人主页',
    `qq` TINYINT(0) ZEROFILL COMMENT 'QQ',
    `description` TEXT COMMENT '个人简介',
    `extra` TEXT COMMENT '其他',
    `user` INT(10) NOT NULL COMMENT '用户',
    `gender` VARCHAR(20) DEFAULT 'male' COMMENT '性别',
    `address` INT(10) COMMENT '联系地址',
    `name_order` VARCHAR(20) NOT NULL DEFAULT 'last_first' COMMENT '姓名顺序',
    PRIMARY KEY (`personal_profile_id`),
    UNIQUE KEY `uk_personal_profile_id_no` (`id_no`),
    KEY `fk_personal_profile_user` (`user`),
    KEY `fk_personal_profile_address` (`address`),
    KEY `ak_personal_profile_display_name` (`display_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='个人档案';