-- TABLE weibo_campaign

CREATE TABLE IF NOT EXISTS `weibo_campaign` (
    `weibo_campaign_id` INT(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    `_task_id` INT(10) COMMENT 'TaskID',
    `name` CHAR(100) NOT NULL COMMENT '名称',
    `start_time` DATETIME NOT NULL COMMENT '起始时间',
    `end_time` DATETIME NOT NULL COMMENT '结束时间',
    `budget` DECIMAL(15,2) COMMENT '预算',
    `total_order` INT(10) NOT NULL DEFAULT 0 COMMENT '总单数',
    `accepted_order` INT(10) NOT NULL DEFAULT 0 COMMENT '接单数',
    `refused_order` INT(10) NOT NULL DEFAULT 0 COMMENT '拒单数',
    `expired_order` INT(10) NOT NULL DEFAULT 0 COMMENT '流单数',
    `paid_order` INT(10) NOT NULL DEFAULT 0 COMMENT '结单数',
    `bad_order` INT(10) NOT NULL DEFAULT 0 COMMENT '坏单数',
    `estimate_cost` DECIMAL(15,2) NOT NULL DEFAULT 0.0 COMMENT '预计支出',
    `estimate_audience` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '预计受众人数',
    `actual_cost` DECIMAL(15,2) NOT NULL DEFAULT 0.0 COMMENT '实际支出',
    `actual_audience` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '实际受众人数',
    `text` VARCHAR(200) COMMENT '文本内容',
    `image` VARCHAR(2083) COMMENT '图片链接',
    `video` VARCHAR(2083) COMMENT '视频链接',
    `retweeting_url` VARCHAR(2083) COMMENT '转发链接',
    `comment` TEXT COMMENT '附加要求',
    `user` INT(10) NOT NULL COMMENT '用户',
    `type` VARCHAR(20) NOT NULL DEFAULT 'post' COMMENT '活动类型',
    `status` VARCHAR(32) NOT NULL DEFAULT 'unpublished' COMMENT '状态',
    `unpublished_time` DATETIME COMMENT '未发布时间',
    `published_time` DATETIME COMMENT '已发布时间',
    `closed_time` DATETIME COMMENT '已结束时间',
    `deleted_time` DATETIME COMMENT '已删除时间',
    `status_log` TEXT COMMENT '状态历史',
    PRIMARY KEY (`weibo_campaign_id`),
    KEY `fk_weibo_campaign_user` (`user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='微博广告活动' AUTO_INCREMENT=1;