-- TABLE weibo_order

CREATE TABLE IF NOT EXISTS `weibo_order` (
    `weibo_order_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    `_is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'IsDeleted',
    `_task_id` INT(10) COMMENT 'TaskID',
    `price` DECIMAL(15,2) NOT NULL COMMENT '金额',
    `service_charge` DECIMAL(15,2) NOT NULL COMMENT '服务费',
    `num_audience` BIGINT(20) NOT NULL COMMENT '受众人数',
    `order_comment` VARCHAR(200) COMMENT '任务备注',
    `finish_url` VARCHAR(2083) COMMENT '任务链接',
    `snapshot_url` VARCHAR(2083) COMMENT '任务截图',
    `tuike_comment` VARCHAR(200) COMMENT '推客备注',
    `refuse_reason` VARCHAR(200) COMMENT '拒单理由',
    `appeal_reason` VARCHAR(200) COMMENT '申诉理由',
    `advertiser_rating` TINYINT(1) COMMENT '广告主评价',
    `advertiser_comment` VARCHAR(200) COMMENT '广告主备注',
    `verifier_comment` VARCHAR(100) COMMENT '审核人备注',
    `campaign` INT(10) NOT NULL COMMENT '微博广告活动',
    `inventory` INT(10) NOT NULL COMMENT '微博渠道',
    `advertiser` INT(10) NOT NULL COMMENT '广告主',
    `tuike` INT(10) NOT NULL COMMENT '推客',
    `status` VARCHAR(32) NOT NULL DEFAULT 'unpublished' COMMENT '状态',
    `unpublished_time` DATETIME COMMENT '未发布时间',
    `published_time` DATETIME COMMENT '已发布时间',
    `accepted_time` DATETIME COMMENT '已接单时间',
    `refused_time` DATETIME COMMENT '拒单时间',
    `expired_time` DATETIME COMMENT '流单时间',
    `cancelled_time` DATETIME COMMENT '已取消时间',
    `submitted_time` DATETIME COMMENT '已提交时间',
    `paid_time` DATETIME COMMENT '已结单时间',
    `appealed_time` DATETIME COMMENT '申诉中时间',
    `processing_time` DATETIME COMMENT '审核中时间',
    `quolified_order_time` DATETIME COMMENT '合格时间',
    `bad_order_time` DATETIME COMMENT '坏单时间',
    `deleted_time` DATETIME COMMENT '已删除时间',
    `status_log` TEXT COMMENT '状态历史',
    `send_method` VARCHAR(20) NOT NULL DEFAULT 'direct' COMMENT '发送方式',
    `advertiser_expense_record` CHAR(20) COMMENT '用户支出记录',
    `tuike_income_record` CHAR(20) COMMENT '用户收入记录',
    `service_income_record` INT(10) COMMENT '平台收入',
    `verifier` INT(10) COMMENT '审核人',
    PRIMARY KEY (`weibo_order_id`),
    UNIQUE KEY `uk_weibo_order_campaign_order` (`campaign`,`inventory`),
    KEY `fk_weibo_order_campaign` (`campaign`),
    KEY `fk_weibo_order_inventory` (`inventory`),
    KEY `fk_weibo_order_advertiser` (`advertiser`),
    KEY `fk_weibo_order_tuike` (`tuike`),
    KEY `fk_weibo_order_advertiser_expense_record` (`advertiser_expense_record`),
    KEY `fk_weibo_order_tuike_income_record` (`tuike_income_record`),
    KEY `fk_weibo_order_service_income_record` (`service_income_record`),
    KEY `fk_weibo_order_verifier` (`verifier`),
    KEY `ak_weibo_order_inventory` (`inventory`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='微博广告任务' AUTO_INCREMENT=1;