#!/bin/bash
#init file for starting up the redis daemon
#
# chkconfig:   - 20 80
# description: Starts and stops the redis daemon.

# Source function library.
. /etc/rc.d/init.d/functions

REDISPORT=__REDIS_PORT__
EXEC=__REDIS_DIR__/bin/redis-server
CLIEXEC=__REDIS_DIR__/bin/redis-cli

PIDFILE=__REDIS_LOG_DIR__/redis.pid
CONF="__REDIS_DIR__/conf/redis.conf"
LOCKFILE="__REDIS_LOG_DIR__/redis.lock"

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
        else
                echo "Starting Redis server..."
                $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running"
        else
                PID=$(cat $PIDFILE)
                echo "Stopping ..."
                PASSWORD=`cat __REDIS_PASSWORD_FILE__`
                $CLIEXEC -p $REDISPORT -a ${PASSWORD} shutdown
                while [ -x /proc/${PID} ]
                do
                    echo "Waiting for Redis to shutdown ..."
                    sleep 1
                done
                echo "Redis stopped"
        fi
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac